version: '3.8'

services:
  app:
    build:
      context: ./src
      dockerfile: ./Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - './src:/app'
      - '/app/node_modules'
    environment:
      - CHOKIDAR_USEPOLLING=true
